### ISSUE TITLE
Ask about a problem that has been miscalculated

### ISSUE THREAD

**Issue by huangjiekaiming** [fevrem/TROPIC#8]
Hello, I'm using Tropic, running main.m, Matlab software prompts syntax error,  the location is varargin (1,:) cell in ld_model.m.
How should I deal with it?

**Comment by sk413025** [comment]
I had the same problem as you, then I commented out all the arguments ... end, and it works fine.

Like the example below, but there are a lot of .m files that need to be commented out like this.

```python
% arguments (Repeating)
%     varargin (1,:) cell
% end
```

**Comment by huangjiekaiming** [comment]
I have solved this problem, you need to use Matlab 2020b.

**Comment by fevrem** [comment]
@huangjiekaiming Thank you for adding the solution. Yes, this functionality was added in Matlab R2019b, so you will need to use R2019b or later.
